### ISSUE TITLE
Pull in latest tokens from figma

### ISSUE THREAD

**Issue by lboehling** [patternfly/design-tokens#87]
Made a few updates to the figma tokens file -- 

**Semantic gap spacers**
- Added semantic gap tokens that @thatblindgeye created in: https://github.com/patternfly/patternfly/pull/6957. Needed to add "--default" to existing group-to-group/horizontal and vertical tokens so they export correctly. 
<img width="400" alt="Screenshot 2024-09-12 at 5 19 37 PM" src="https://github.com/user-attachments/assets/02c3d78e-c0e8-4fd3-83a8-a1acec7fcc98">

**Color tokens to support read-only controls**
- Added global/border/color/50 and global/dark/border/color/50
- Added global/border/color/control/read-only
- Added global/background/color/control/read-only
<img width="872" alt="Screenshot 2024-09-12 at 5 17 53 PM" src="https://github.com/user-attachments/assets/3e6b7475-70ea-46b2-b1ac-b1aa6ac8c4d9">

**DPO Typography Updates** 
- Base tokens:  Increases our font--size--600 and icon--size--300 from 22px to 24px. 
- Base tokens: Adjusts font--weight--300 from 700 to 500
- Base tokens: Also adjusted figma only line-height value, but that should be filtered out. 
<img width="569" alt="Screenshot 2024-09-12 at 5 19 24 PM" src="https://github.com/user-attachments/assets/421e4979-65de-4344-aac9-fbb0be7907a4"> 

Will create core issues for follow-up work

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/7075
