### ISSUE TITLE
New and Updated tokens for directional box-shadows

### ISSUE THREAD

**Issue by lboehling** [patternfly/design-tokens#89]
Added a handful of new design tokens and updated a few existing tokens to support directional box-shadows. Design specs are detailed in this issue: https://github.com/patternfly/patternfly-design/issues/1310. 

Will need to pull in tokens from Figma again and update the local box-shadow tokens to use the new spread semantic tokens for directional shadows. 

@mcoker

**Comment by lboehling** [comment]
@mcoker made a few more updates to the directional box shadows. these changes are up to date in figma -- 
<img width="746" alt="Screenshot 2024-09-23 at 6 24 53 PM" src="https://github.com/user-attachments/assets/e6391bbd-ac18-4783-86a6-411dc18d7023">

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/design-tokens/pull/93
